// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/spark/fides-bff/internal/biz"
	"github.com/spark/fides-bff/internal/conf"
	"github.com/spark/fides-bff/internal/server"
	"github.com/spark/fides-bff/internal/service"
)

// Injectors from wire.go:

// wireApp assembles the application from config, build version, and logger.
//
// Providers are listed here in the bootstrap layer so the inner packages
// (biz/service/server) stay free of the wire DI framework, per the team
// backend clean-architecture rule that domain/application must not depend on
// DI frameworks.
func wireApp(confServer *conf.Server, version biz.Version, logger log.Logger) (*kratos.App, func(), error) {
	healthUsecase := biz.NewHealthUsecase(version)
	healthService := service.NewHealthService(healthUsecase)
	httpServer := server.NewHTTPServer(confServer, healthService)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
