// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/spark/bffkit"
	"github.com/spark/fides-bff/internal/biz"
	"github.com/spark/fides-bff/internal/conf"
	"github.com/spark/fides-bff/internal/data"
	"github.com/spark/fides-bff/internal/server"
	"github.com/spark/fides-bff/internal/service"
	"log/slog"
	"time"
)

// Injectors from wire.go:

// wireApp assembles the application from config, build version, and logger.
//
// Providers are listed here in the bootstrap layer so the inner packages
// (biz/service/server) stay free of the wire DI framework, per the team
// backend clean-architecture rule that domain/application must not depend on
// DI frameworks.
func wireApp(confServer *conf.Server, applicant *conf.Applicant, quote *conf.Quote, origination *conf.Origination, auth *conf.Auth, registry *conf.Registry, observability conf.Observability, version biz.Version, logger *slog.Logger) (*kratos.App, func(), error) {
	healthUsecase := biz.NewHealthUsecase(version)
	healthService := service.NewHealthService(healthUsecase)
	applicantAuthClient := data.NewApplicantAuthClient(applicant)
	authUsecase := biz.NewAuthUsecase(applicantAuthClient)
	authService := service.NewAuthService(authUsecase)
	quoteClient := data.NewQuoteClient(quote)
	pricingUsecase := biz.NewPricingUsecase(quoteClient)
	pricingService := service.NewPricingService(pricingUsecase)
	originationClient := data.NewOriginationClient(origination)
	originationUsecase := biz.NewOriginationUsecase(originationClient)
	originationService := service.NewOriginationService(originationUsecase)
	identityProfileUsecase := biz.NewIdentityProfileUsecase(applicantAuthClient, originationClient)
	identityProfileService := service.NewIdentityProfileService(identityProfileUsecase)
	sessionTokenValidator := data.NewSessionTokenValidator(auth)
	idempotencyStore := newIdempotencyStore()
	httpServer := server.NewHTTPServerWithObservability(confServer, healthService, authService, pricingService, originationService, identityProfileService, observability, sessionTokenValidator, idempotencyStore, logger)
	mainRegistration, err := newConsulRegistration(registry)
	if err != nil {
		return nil, nil, err
	}
	app := newApp(logger, httpServer, mainRegistration)
	return app, func() {
	}, nil
}

// wire.go:

func newIdempotencyStore() bffkit.IdempotencyStore {
	return bffkit.NewMemoryIdempotencyStore(24 * time.Hour)
}
