//go:build wireinject
// +build wireinject

// The build tag makes sure this file is excluded from normal builds; wire_gen.go
// (generated by `make generate`) holds the real injector.
package main

import (
	"time"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/google/wire"
	"github.com/spark/bffkit"

	"github.com/spark/fides-bff/internal/biz"
	"github.com/spark/fides-bff/internal/conf"
	"github.com/spark/fides-bff/internal/data"
	"github.com/spark/fides-bff/internal/server"
	"github.com/spark/fides-bff/internal/service"
)

// wireApp assembles the application from config, build version, and logger.
//
// Providers are listed here in the bootstrap layer so the inner packages
// (biz/service/server) stay free of the wire DI framework, per the team
// backend clean-architecture rule that domain/application must not depend on
// DI frameworks.
func wireApp(*conf.Server, *conf.Applicant, *conf.Quote, *conf.Origination, *conf.Auth, *conf.Registry, biz.Version, log.Logger) (*kratos.App, func(), error) {
	panic(wire.Build(
		biz.NewHealthUsecase,
		biz.NewAuthUsecase,
		biz.NewPricingUsecase,
		biz.NewOriginationUsecase,
		biz.NewIdentityProfileUsecase,
		data.NewApplicantAuthClient,
		data.NewQuoteClient,
		data.NewOriginationClient,
		data.NewOriginationDraftClient,
		data.NewSessionTokenValidator,
		wire.Bind(new(biz.ApplicantAuthClient), new(*data.ApplicantAuthClient)),
		wire.Bind(new(biz.ApplicantProfileClient), new(*data.ApplicantAuthClient)),
		wire.Bind(new(biz.QuoteClient), new(*data.QuoteClient)),
		wire.Bind(new(biz.OriginationClient), new(*data.OriginationClient)),
		wire.Bind(new(biz.OriginationDraftClient), new(*data.OriginationDraftClient)),
		wire.Bind(new(bffkit.TokenValidator), new(*data.SessionTokenValidator)),
		service.NewHealthService,
		service.NewAuthService,
		service.NewPricingService,
		service.NewOriginationService,
		service.NewIdentityProfileService,
		newIdempotencyStore,
		newConsulRegistration,
		server.NewHTTPServer,
		newApp,
	))
}

func newIdempotencyStore() bffkit.IdempotencyStore {
	return bffkit.NewMemoryIdempotencyStore(24 * time.Hour)
}
